"""ActionBuilder 使用的宿主 Worker/Inline Prompt 合同。"""

from __future__ import annotations

# 严格 spawn Action 只描述原生执行事实；证明与 Result 由 Assembler 独占生成。
SPAWN_INSTRUCTION = (
    "Execute exactly {count} native worker{parallel} from spawn.invocations[] "
    "with requested effort={effort}.\n"
    "Execute every project tool and launch every worker with working directory "
    "{project_root}; never use the plugin or prompt-artifact directory as cwd.\n"
    "The binding design document is read-only; never edit it or add metadata. "
    "If a design change is necessary, return only design_change_requests[] and wait for the user Gate.\n"
    "All file_targets and file_list values must be POSIX paths relative to the project root; "
    "never emit absolute paths.\n"
    "{multi_instruction}"
    "Each Worker should write its own business outcome JSON atomically to the invocation's "
    "outcome_path before it returns. The native Agent final response must also contain "
    "exactly one structured business JSON object (prefer the same worker_id/status/payload/summary "
    "artifact, with no Markdown). The private file is an envelope, not the payload: write "
    'exactly {{"worker_id":"<worker_id>","status":"completed","payload":{{...}},"summary":"..."}}; '
    "never write business fields directly at the private-file root. Host Driver must persist "
    "the exact native return envelope "
    "unchanged to native_result_path before reading the private artifact; if the private "
    "artifact is missing, the single record-worker-outcome boundary will strictly extract "
    "and atomically materialize it. if the private artifact exists but is invalid, preserve it "
    "and report the structured same-Action repair error; never overwrite it from native text. "
    "The private artifact may contain only worker_id, "
    "status, payload and summary; put every expected_format business field inside payload "
    "(for example batch_id, files_changed and test_results), never beside payload. "
    "Use canonical status completed/failed/cancelled/timed_out; "
    "complete/success/ok are accepted only as completion aliases at the Host handoff boundary. "
    "Do not write native_worker_handle, actual_model, "
    "isolation_evidence, attestation, receipt or shared outcomes; Host Driver must obtain "
    "those facts from the native API and Host Collector will merge them into the shared "
    "\"outcomes\" file. Coordinator writes only expected_format business fields to "
    "The Host Driver, not the Worker, uses the model identifier reported by the native "
    "worker API for actual_model; if unavailable it records actual_model='unreported' "
    "without guessing. The Host Driver records actual isolation evidence from the native "
    "execution context; a completed Worker without it must fail closed, and its status must "
    "match the Worker business artifact. The Worker must not copy "
    "spawn.invocations[].isolation or invent evidence. "
    "A Worker must not invoke Agent/Task/collaboration or create nested workers; "
    "the current Action's invocation is the only allowed Worker boundary. "
    "Host hooks distinguish the Coordinator from a fresh native Worker using the "
    "runtime-provided top-level agent_id; Coordinator tool calls must never write "
    "worker-outcomes, while a Worker may write only its own private business artifact. "
    "Coordinator must never Read the worker prompt_ref, mkdir, list or inspect worker-outcomes, "
    "native-results or private outcome directories; Host Runtime pre-creates the bound "
    "directories. Use only the compact Action, the native "
    "return envelope and the bound record/finalize operations. A hook refusal on those paths "
    "is a protocol boundary, not permission to switch to another tool or manually repair state. "
    "action.host_execution.work_files.coordinator_result. Do not write receipt, "
    "attestation, proof, spawned, "
    "spawn_proof_token, or protocol identity fields.\n"
    "Execute action.host_execution.operations.finalize.argv, validate.argv and "
    "submit.argv in order; replace only __AE_BUNDLED_RUNNER__ with the fixed bundled "
    "runner and never rebuild, reorder or copy their path arguments. "
    "Never reuse files from another Action. "
    "The Assembler is the "
    "only proof and Result writer.\n"
    "Before evaluating action.spawn, inspect action.host_execution.recovery. "
    "If recovery exists with spawn_permitted=false, recovery is the only legal branch: "
    "do not call Agent, Task, TaskOutput or any other Worker tool; do not reconstruct "
    "a native prompt; use only the recovery work_files and bound finalize/validate/submit "
    "operations, repairing coordinator_result only when the recovery contract permits it.\n"
    "After each native Worker returns, read only that invocation's private outcome_path; "
    "always persist the exact native return envelope (without editing its JSON) "
    "to that invocation's native_result_path before invoking the bundled dev-loop "
    "--record-worker-outcome argv_template command, replacing every runtime placeholder "
    "with the native status, handle, model and actual isolation evidence. The final command "
    "must contain literal argv values: never assign AE_INVOCATION_PROJECT_ROOT, ROOT, RUNNER "
    "or another shell variable and never use $VAR, command substitution or pwd for any "
    "template argument. Copy the template's literal --native-result-file path exactly and "
    "copy the Action's literal absolute project_root exactly for --project-root; the hook "
    "validates raw command text before shell expansion. The fixed template "
    "also accepts the exact envelope on stdin via --native-result-stdin while retaining "
    "the template's bound --native-result-file path, so do not use "
    "shell JSON arguments, Bash heredocs, or hand-written temporary files. "
    "If the native tool result cannot be passed byte-for-byte, stop with "
    "HOST_EVIDENCE_INVALID; never reconstruct or summarize a native envelope. Use the literal "
    "unreported sentinel only when a failed native call exposes no handle/evidence; "
    "never hand-edit shared outcomes or invent completed evidence. "
    "The native tool return is completion/host evidence plus a strictly parsed business-result "
    "handoff input; it never supplies native handle/model/isolation fields. "
    "For Claude Code, invoke the native Agent tool with native_launch_prompt verbatim; "
    "the stage prompt/prompt_ref is Worker input, not the Agent tool argument. If the "
    "Hook reports NATIVE_LAUNCH_PROMPT_MISMATCH, do not report missing capability or "
    "end the Action: reread the compact Action field and retry the same Agent call. "
    "if Agent returns async_launched, running or pending, call TaskOutput with the same "
    "agentId/task_id until completed; do not Stop, TaskStop, Read, Bash, restart or write "
    "any state while it is running. Only the completed native envelope may be recorded. "
    "use the exact Agent/Task return agentId or task id as native_worker_handle, use "
    "actual_model=unreported only when the native return omits model, and use "
    "fresh_context for the native isolation evidence. For Codex, use the exact native "
    "collaboration agent/thread id and set isolation_evidence to the exact "
    "host_execution.workers[].expected_isolation_evidence value (fork_turns=none); "
    "do not replace it with a generic label such as native_context.\n"
    "After tick returns the next Action, discard every prior Action object, work-file "
    "path, worker handle and command argument. Do not print full diffs, prior outcomes "
    "or historical Action JSON during recovery; consume only the structured error and "
    "the active Action.\n"
    "If native spawn reports capacity exhaustion, first wait for known workers to finish "
    "and reclaim their handles when the host supports it, then retry once. If capacity is "
    "still unavailable, report HOST_AGENT_CAPACITY without fabricating a worker result."
    " If any native worker times out or fails, record that native failure in outcomes, "
    "write an empty coordinator payload, and call the same Finalizer; never fabricate "
    "business fields or success evidence."
    " If the Worker observes test_results.failed != 0 or test_results.errors != 0, "
    "the Worker result is not a completed business result: preserve the exact private "
    "outcome, use record-worker-outcome with status=failed, write an empty coordinator "
    "payload and call the bound failure/finalize path. The Coordinator must not edit "
    "the private outcome, change failed/errors to zero, or turn red_evidence into "
    "completed success."
    " After recording every completed outcome, immediately close or reclaim that native "
    "worker handle before advancing to another Action. If a hook rejects the record command, "
    "retry that same command after correcting only the reported literal argument; never use "
    "cat, tee, redirection or Write to create/edit .ae-state/host-runtime/worker-outcomes, "
    "and never interpret this protocol rejection as a missing tool or a user approval request."
)
SPAWN_MULTI_INSTRUCTION = (
    "Use each invocation's prompt_ref, prompt_sha256, isolation, receipt_path and outcome_path; "
    "each worker writes only its own outcome_path, never shared state.\n"
)
SPAWN_SINGLE_INSTRUCTION = (
    "Use spawn.invocations[0] as the only execution contract.\n"
)
# Non-spawn stages (developer, gap_scan inline) use this:
INLINE_INSTRUCTION = (
    "Do the work for stage '{stage}' per expected_format. "
    "Write result JSON with stage='{stage}'."
)
__all__ = [
    "INLINE_INSTRUCTION",
    "SPAWN_INSTRUCTION",
    "SPAWN_MULTI_INSTRUCTION",
    "SPAWN_SINGLE_INSTRUCTION",
]
